### ISSUE TITLE
Programação dos posts

### ISSUE THREAD

**Issue by DarkstaIkers** [lucasljj/bhd8#132]
Por algum motivo misterioso o site perdeu a homogenia, e virou uma terra sem lei. Basta ter um post - que logo em seguida vem outro cima. Na minha singela opinião, se foi postado um post no dia X, o tempo mínimo para um novo post devia ser de 24 horas (um dia), assim evitaríamos posts duplos ou até mesmo triplos na home do site no mesmo dia. O site passaria a ter posts diários e não essa desorganização de um querendo passar na frente do outro.

**Comment by lucasljj** [comment]
É, é algo a se pensar... lembro que um dia isso já foi assim

**Comment by DarkstaIkers** [comment]
'-'
