### ISSUE TITLE
Adicionar links de navegação estrutural no layout

### ISSUE THREAD

**Issue by lucasljj** [lucasljj/bhd8#134]
Isso vai ser bem útil para os usuários voltarem a série :)

![image](http://i.imgur.com/BtYY2rS.png)

Na v3 além do breadcrumb o usuário pode voltar usando os links de navegação do módulo book, não seria legal perdermos essa funcionalidade tão útil (o breadcrumb)
![image](http://i.imgur.com/VB2Thmi.jpg)

**Comment by DarkstaIkers** [comment]
Pois é, mas em que parte ficaria essa opção?

**Comment by DarkstaIkers** [comment]
Pensamento melhor, se tivesse o cabeçalho "VOCÊ ESTÁ AQUI INÍCIO » HENTAIS » Oni Chichi... já ficaria como é na v3

**Comment by lucasljj** [comment]
Isso aí, o breadcrumb é exatamente isso kkkk

**Comment by DarkstaIkers** [comment]
Jurava que era essa parte aqui http://i.imgur.com/jvdAQrU.png hihihi

**Comment by lucasljj** [comment]
Fazer isso é meio fácil, como esse bagulho vai ser exibido é verdadeira a treta `-`

O fundo muda em todas as páginas do site, tornando bem difícil a escolha de uma cor de fonte pra essa bagaça

**Comment by DarkstaIkers** [comment]
Tive algumas ideias, saca só:
http://i.imgur.com/kzfwxih.png
http://i.imgur.com/2GPtn8F.png
http://i.imgur.com/2Vt7Peo.png
Mexer no layout não é uma opção, creio eu.

**Comment by DarkstaIkers** [comment]
Ahhh... http://i.imgur.com/IFjmLhk.jpg
