### ISSUE TITLE
Não exibir "seu voto" para usuários anônimos

### ISSUE THREAD

**Issue by lucasljj** [lucasljj/bhd8#17]
Alterar o widget do fivestar para não exibir "seu voto" para usuários anônimos

<h3>Propostas de resolução</h3>
 - Fazer isso criando um novo campo (evitaria css extra ou javascript extra) mas, causaria uma carga extra(mínima) no site
 - Fazer isso com css ou javascript

**Comment by Lucasljj** [comment]
Humm... acho que com css é algo mais limpo, parece menos uma gambiarra

**Comment by lucasljj** [comment]
Nem vamos ter espaço para isso mesmo..
![image](http://i.imgur.com/dFk7h58.png)
