### ISSUE TITLE
Implantar o formulário de comentários do PAI do episódio na página do episódio

### ISSUE THREAD

**Issue by lucasljj** [lucasljj/bhd8#18]
engajamento dos fapers ++

**Comment by Lucasljj** [comment]
Hummm... pensando bem... talvez não assim não fique algo tão intuitivo, a galera costuma comentar coisas relacionadas ao episódio na página do episódio, como acontece nos outros sites semrpe que sai um episódio novo do naruto rola milhares de xingametos ao autor por aquele episódio ter sido tão ruim...

**Comment by lucasljj** [comment]
non, é melhor deixar os comentários dos episódios nOS episódios
