### ISSUE TITLE
Criar um módulo de download das imagens do capítulo

### ISSUE THREAD

**Issue by lucasljj** [lucasljj/bhd8#2]
Já podemos fazer o download de capítulos individuais, portanto, não é mais um bloqueador
- [x] Download do capítulo - necessário para concluir #1
- [x] ~~Download do mangá completo~~

**Comment by Lucasljj** [comment]
Parece fácil, basta fazer uma junção de vários arrays com as informações de onde a pasta de imagens de cada node esta e depois zipar tudo usando alguma função do drupal ou biblioteca externa

**Comment by Lucasljj** [comment]
![Era pra ser um diagrama de atividas, mas... já foi](http://i.imgur.com/Sm0NOqM.png)
Era pra ser um diagrama de atividas, mas... já foi

**Comment by lucasljj** [comment]
'-' já existe um módulo que faz a mesma coisa https://www.drupal.org/project/file_compressor_field, só que melhor kkk

Mas, de qualquer, forma, ele também não implementa uma funcionalidade que a gente precisa, então isso continua aberto e agora temos uma fonte de melhores práticas para essa área *-*
