### ISSUE TITLE
Remover a dependência do módulo views_slideshow

### ISSUE THREAD

**Issue by lucasljj** [lucasljj/bhd8#3]
<h1>Motivação</h1>
É um módulo desncessário que fornecesse uma funcionalidade muito simples de ser implementada usando um pouco de código + views. Isso faz parte do plano #53 de deixar o site mantível :)

<h1>Proposta de Resolução</h1>
Criar algo prórpio usando uma view comum no formato bloco(pra não ter que usar o views_embed_view)

**Comment by Lucasljj** [comment]
Feito :)

**Comment by lucasljj** [comment]
Hum... acho que isso vai ter que ser reaberto pra usar outra biblioteca ou construir alguma própria que não dependa de jQuery

**Comment by lucasljj** [comment]
<h1>NOVA Proposta de Resolução</h1>
Isso não precisa usar realmente o views, é algo mudará beeem pouco durante a vida do novo tema do site, então... assim como alguns outros blocos mencionados em #110, deve ser mais performático ter isso num template customizado
