### ISSUE TITLE
FTP do site sempre on

### ISSUE THREAD

**Issue by ghost** [lucasljj/bhd8#43]
Vira e mexe o FTP fica on/off, já que estamos fazendo uma lista de bugs, melhorias e afins. Acho que está na hora desse FTP decolar!

**Comment by Lucasljj** [comment]
ISSO! isso sim é algo pelo qual vale a pena lutarmos!

**Comment by lucasljj** [comment]
Não vai ser necessário, o controle de arquivos vai ser feito diretamente no site
