### ISSUE TITLE
Melhorar o sistema de comentários

### ISSUE THREAD

**Issue by lucasljj** [lucasljj/bhd8#52]
<h2>Oi?</h2>
Comentários são o grande "BAM" do engajamento... uma experiência de usuário prazerosa geralmente(será que isso funciona com a gente?) faz o usuário querer comentar... o problema é que o sistema de comentários padrão do Drupal é bem maisoumenos, poderíamos ter um módulo que funcionasse como o disqus, com ajax (bem dinâmico), notificações e beem bonito :)

<h2>Como</h2>
Com comentários AJAX

<h2>COm quantas?</h2>
- [x] Respostas inline, tipo o Disqus
- [ ] Emojis (do google)
- [ ] Ordenação personalizada (mais recentes e mais "curtidos")
- [ ] usar os dados do contador de comentários do Drupal, já tem um tabela com algo do tipo "comment statistcs" 
- [ ] Curtir comentário

**Comment by Lucasljj** [comment]
Humm... depois de a ideia passar alguns dias de molho... acredito que o melhor seja usar emojis (os do google), que são beeem mais leves http://www.emoji-cheat-sheet.com/

**Comment by lucasljj** [comment]
da pra exportar a view, mas não tô com saco pra procurar ela no meio daqueles arquivos...
![view dos comentários](http://i.imgur.com/gXrsnoA.png)

**Comment by lucasljj** [comment]
Respostas encadeadas até parecem legais, mas, em grandes discussões isso acaba ficando horrível, o ideal seria que tivéssemos um limite de profundidade, por enquanto um exemplo com profundidade máxima 2
![image](http://i.imgur.com/gNWyuae.png)

![image](http://i.imgur.com/XOqBJyD.jpg)

**Comment by lucasljj** [comment]
estrutura dos novos comentários em json:

{  
    "have_children": "true"
    "cid":"31516",
    "pid":"",
    "name":"lucas",
    "comment_body":"<p>hahaha<\/p>",
    "parent_name":"",
    "created":"2 days ago"
}

**Comment by lucasljj** [comment]
É... só tenho que arrajar um lugar pra esse botão de enviar comentário
![image](http://i.imgur.com/abOUB40.png)

**Comment by lucasljj** [comment]
Comecemos com uma história, num passado distante, ou não tão distante assim, usuários logados poderiam

O esquema para reimplementar o histórico de comentários "novos" ou não é fazer o seguinte:
- verificar via javascript se a data de envio do comentário é maior que a data da última visualização do post
  - se for maior exibir uma tagzinha com "novo" ao lado do nome do autor, semelhante ao que acontece atualmente

Como a data de visualização vai ser atualizada automaticamente

**Comment by lucasljj** [comment]
É... pra evitar CSRF a gente tem que primeiro pedir um token antes de enviar o comentário

**Comment by lucasljj** [comment]
![image](http://i.imgur.com/RZ0dU5Z.png)

legal, acho que dá pra shipar assim
