### ISSUE TITLE
Criar um vps com windows dentro do servidor do site

### ISSUE THREAD

**Issue by lucasljj** [lucasljj/bhd8#64]
Isso precisa ter uma senha últra mega fodastica e ter várias cadamas de segurança, provavelmente aquelas isos da ms com ieca sirvam pra isso *-*

**Comment by EduardoRFS** [comment]
Só uma pergunta para que uma vps com windows?

**Comment by v1touch** [comment]
O VPS seria pra encode e upload?

**Comment by Lucasljj** [comment]
E encode, eu acho...

**Comment by lucasljj** [comment]
Non, esse trabalho de encode já vai ser feito por outros bagulhos magicamente
