### ISSUE TITLE
HHVM ou PHP7?

### ISSUE THREAD

**Issue by lucasljj** [lucasljj/bhd8#80]
HHVM parece bem rápido, as páginas dos hentais estão sendo processadas em apenas 65~80ms(sem comentário algum), mas aparentemente quando uma página precisa processar os templates do twig isso acaba deixando as coisas um pouco mais lentas, precisamos de testes com PHP 7 para fazer uma comparação

a extensão em C do twig com certeza deve sair para o PHP 7 o que talvez lhe dê uma vantagem sobre HHVM

**Comment by EduardoRFS** [comment]
Nas analises que eu já vi o php7 sempre bate no hhvm, e o drupal 8 já ta sendo preparado o php7.

**Comment by lucasljj** [comment]
Né, parece ganhar na maioria das vezes :), deixei isso aberto porque o HHVM ainda não usa PHP7, talvez quando usarem as coisas fiquem mais rápidas ainda

**Comment by lucasljj** [comment]
E já que o site não deve sair antes do php7 \`-\`

**Comment by lucasljj** [comment]
php7
